leftnav:
- identifier: 3403163d-758b-6714-1631-a149079aa07d
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: a44c8782-2f12-6a98-ecb0-0fbd8593deb3
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 8588870e-08b4-2117-9828-ac7772b347b5
  name: Assignments
  url: /pages/assignments
  weight: 30
